### ISSUE TITLE
After update, logs not working, images gone.

### ISSUE THREAD

**Issue by tr1p0p** [YunoHost-Apps/bookstack_ynh#36] opened 2021-07-19 12:04 UTC
So, after update on RPI 4 with yunohost install. EVERY update Bookstack it's break ALL images path, and also break access for the admin account.

Basically every update is pretty scary, i don't even know how it can lost ALL images at every update, can't make a wiki with this..

What can i do ?

**Comment by tr1p0p** [comment] 2021-07-19 12:15
![Screenshot 2021-07-19 at 14-08-46 NullWiki](https://user-images.githubusercontent.com/37407065/126158264-9d0a187f-5805-4aeb-a065-55a4c4f052c9.png)

**Comment by ericgaspar** [comment] 2021-07-19 13:08
Sorry for the problem.
As I am not using myself the app and no one as reported so far it seems that the bug went under the radar...
Not sure what the problem is. I created a branch where PHP as been updated to version 8.0. If you are willing to test you feed back will be appreciated
`sudo yunohost app upgrade bookstack -u https://github.com/YunoHost-Apps/bookstack_ynh/tree/patch--force`

**Comment by tr1p0p** [comment] 2021-07-21 17:31
So, update with this seem to run fine, but still a "unknown error occurred" when trying to log in..

**Comment by marcelcosta** [comment] 2021-10-04 14:13
I have this error too!

If you need any information, please ask.

**Comment by da-am** [comment] 2021-10-04 16:04
I've been getting this for a few months as well. The folder permissions look ok, bookstack www-data. Is there something to look for to fix this?

**Comment by weex** [comment] 2021-11-30 16:36
Does https://www.bookstackapp.com/docs/admin/debugging/#broken-links-or-no-images-after-app_url-change help?

**Comment by da-am** [comment] 2021-12-01 16:06
Thanks for that! My logs showed database errors left and right. I was going to start over but saw that there is a migrate command for the database so I ran php artisan migrate. Now everything works again. I guess the last update didn't fire off the migrate command properly?

**Comment by weex** [comment] 2021-12-01 16:52
Interesting, the script looks ok to me but yes if you have any logs around the update they may be helpful for future troubleshooting. Feel free to close this if your issue is resolved.

**Comment by marcelcosta** [comment] 2021-12-01 17:53
I did the job for me too!

Thanks.

**Comment by ericgaspar** [comment] 2022-01-29 14:33
#38 should solve the issue of lost images after upgrade.
Bewar, we still have issues with the change url script not working in all configuration.

**Closed** 2022-01-29 22:50 UTC
